# config.py
import os

# Токены ботов
ADMIN_BOT_TOKEN = "8310541753:AAH3oJtmhdqbIQFNs4ZH7HsP_8rdQaMaFKo"
USER_BOT_TOKEN = "8356415375:AAHYvpAlCBFplUQ6rN0KgN9_AvB8Bje37KY"

# ID канала и администратора
CHANNEL_ID = -1003182432409
ADMIN_ID = 5912983856

# Mistral AI API ключ
MISTRAL_API_KEY = "SAIPWn5nSCdvXGFFV6DLkoXnk3T31pcX"

# Названия сур на разных языках (все 114 сур)
SURA_NAMES = {
    1: {'ar': 'الفاتحة', 'uz': 'Fotiha', 'ru': 'Аль-Фатиха', 'en': 'Al-Fatihah'},
    2: {'ar': 'البقرة', 'uz': 'Baqara', 'ru': 'Аль-Бакара', 'en': 'Al-Baqarah'},
    3: {'ar': 'آل عمران', 'uz': 'Al-Imron', 'ru': 'Аль Имран', 'en': 'Al-Imran'},
    4: {'ar': 'النساء', 'uz': 'Niso', 'ru': 'Ан-Ниса', 'en': 'An-Nisa'},
    5: {'ar': 'المائدة', 'uz': 'Moida', 'ru': 'Аль-Маида', 'en': 'Al-Maidah'},
    6: {'ar': 'الأنعام', 'uz': 'An\'om', 'ru': 'Аль-Анам', 'en': 'Al-Anam'},
    7: {'ar': 'الأعراف', 'uz': 'A\'rof', 'ru': 'Аль-Араф', 'en': 'Al-Araf'},
    8: {'ar': 'الأنفال', 'uz': 'Anfol', 'ru': 'Аль-Анфаль', 'en': 'Al-Anfal'},
    9: {'ar': 'التوبة', 'uz': 'Tavba', 'ru': 'Ат-Тауба', 'en': 'At-Tawbah'},
    10: {'ar': 'يونس', 'uz': 'Yunus', 'ru': 'Юнус', 'en': 'Yunus'},
    11: {'ar': 'هود', 'uz': 'Hud', 'ru': 'Худ', 'en': 'Hud'},
    12: {'ar': 'يوسف', 'uz': 'Yusuf', 'ru': 'Юсуф', 'en': 'Yusuf'},
    13: {'ar': 'الرعد', 'uz': 'Ra\'d', 'ru': 'Ар-Раад', 'en': 'Ar-Rad'},
    14: {'ar': 'إبراهيم', 'uz': 'Ibrohim', 'ru': 'Ибрахим', 'en': 'Ibrahim'},
    15: {'ar': 'الحجر', 'uz': 'Hijr', 'ru': 'Аль-Хиджр', 'en': 'Al-Hijr'},
    16: {'ar': 'النحل', 'uz': 'Nahl', 'ru': 'Ан-Нахль', 'en': 'An-Nahl'},
    17: {'ar': 'الإسراء', 'uz': 'Isro', 'ru': 'Аль-Исра', 'en': 'Al-Isra'},
    18: {'ar': 'الكهف', 'uz': 'Kahf', 'ru': 'Аль-Кахф', 'en': 'Al-Kahf'},
    19: {'ar': 'مريم', 'uz': 'Maryam', 'ru': 'Марьям', 'en': 'Maryam'},
    20: {'ar': 'طه', 'uz': 'Toha', 'ru': 'Та-Ха', 'en': 'Ta-Ha'},
    21: {'ar': 'الأنبياء', 'uz': 'Anbiyo', 'ru': 'Аль-Анбия', 'en': 'Al-Anbiya'},
    22: {'ar': 'الحج', 'uz': 'Haj', 'ru': 'Аль-Хадж', 'en': 'Al-Hajj'},
    23: {'ar': 'المؤمنون', 'uz': 'Muminun', 'ru': 'Аль-Муминун', 'en': 'Al-Muminun'},
    24: {'ar': 'النور', 'uz': 'Nur', 'ru': 'Ан-Нур', 'en': 'An-Nur'},
    25: {'ar': 'الفرقان', 'uz': 'Furqon', 'ru': 'Аль-Фуркан', 'en': 'Al-Furqan'},
    26: {'ar': 'الشعراء', 'uz': 'Shuaro', 'ru': 'Аш-Шуара', 'en': 'Ash-Shuara'},
    27: {'ar': 'النمل', 'uz': 'Naml', 'ru': 'Ан-Намль', 'en': 'An-Naml'},
    28: {'ar': 'القصص', 'uz': 'Qasas', 'ru': 'Аль-Касас', 'en': 'Al-Qasas'},
    29: {'ar': 'العنكبوت', 'uz': 'Ankabut', 'ru': 'Аль-Анкабут', 'en': 'Al-Ankabut'},
    30: {'ar': 'الروم', 'uz': 'Rum', 'ru': 'Ар-Рум', 'en': 'Ar-Rum'},
    31: {'ar': 'لقمان', 'uz': 'Luqmon', 'ru': 'Лукман', 'en': 'Luqman'},
    32: {'ar': 'السجدة', 'uz': 'Sajda', 'ru': 'Ас-Саджда', 'en': 'As-Sajdah'},
    33: {'ar': 'الأحزاب', 'uz': 'Ahzob', 'ru': 'Аль-Ахзаб', 'en': 'Al-Ahzab'},
    34: {'ar': 'سبأ', 'uz': 'Saba', 'ru': 'Саба', 'en': 'Saba'},
    35: {'ar': 'فاطر', 'uz': 'Fotir', 'ru': 'Фатир', 'en': 'Fatir'},
    36: {'ar': 'يس', 'uz': 'Yasin', 'ru': 'Йа-Син', 'en': 'Ya-Sin'},
    37: {'ar': 'الصافات', 'uz': 'Soffat', 'ru': 'Ас-Саффат', 'en': 'As-Saffat'},
    38: {'ar': 'ص', 'uz': 'Sod', 'ru': 'Сад', 'en': 'Sad'},
    39: {'ar': 'الزمر', 'uz': 'Zumar', 'ru': 'Аз-Зумар', 'en': 'Az-Zumar'},
    40: {'ar': 'غافر', 'uz': 'G\'ofir', 'ru': 'Гафир', 'en': 'Ghafir'},
    41: {'ar': 'فصلت', 'uz': 'Fussilat', 'ru': 'Фуссилат', 'en': 'Fussilat'},
    42: {'ar': 'الشورى', 'uz': 'Shuro', 'ru': 'Аш-Шура', 'en': 'Ash-Shura'},
    43: {'ar': 'الزخرف', 'uz': 'Zuxruf', 'ru': 'Аз-Зухруф', 'en': 'Az-Zukhruf'},
    44: {'ar': 'الدخان', 'uz': 'Duxon', 'ru': 'Ад-Духан', 'en': 'Ad-Dukhan'},
    45: {'ar': 'الجاثية', 'uz': 'Josiya', 'ru': 'Аль-Джасия', 'en': 'Al-Jathiyah'},
    46: {'ar': 'الأحقاف', 'uz': 'Ahqof', 'ru': 'Аль-Ахкаф', 'en': 'Al-Ahqaf'},
    47: {'ar': 'محمد', 'uz': 'Muhammad', 'ru': 'Мухаммад', 'en': 'Muhammad'},
    48: {'ar': 'الفتح', 'uz': 'Fath', 'ru': 'Аль-Фатх', 'en': 'Al-Fath'},
    49: {'ar': 'الحجرات', 'uz': 'Hujurot', 'ru': 'Аль-Худжурат', 'en': 'Al-Hujurat'},
    50: {'ar': 'ق', 'uz': 'Qof', 'ru': 'Каф', 'en': 'Qaf'},
    51: {'ar': 'الذاريات', 'uz': 'Zoriyot', 'ru': 'Аз-Зарият', 'en': 'Adh-Dhariyat'},
    52: {'ar': 'الطور', 'uz': 'Tur', 'ru': 'Ат-Тур', 'en': 'At-Tur'},
    53: {'ar': 'النجم', 'uz': 'Najm', 'ru': 'Ан-Наджм', 'en': 'An-Najm'},
    54: {'ar': 'القمر', 'uz': 'Qamar', 'ru': 'Аль-Камар', 'en': 'Al-Qamar'},
    55: {'ar': 'الرحمن', 'uz': 'Rahman', 'ru': 'Ар-Рахман', 'en': 'Ar-Rahman'},
    56: {'ar': 'الواقعة', 'uz': 'Voqia', 'ru': 'Аль-Вакиа', 'en': 'Al-Waqiah'},
    57: {'ar': 'الحديد', 'uz': 'Hadid', 'ru': 'Аль-Хадид', 'en': 'Al-Hadid'},
    58: {'ar': 'المجادلة', 'uz': 'Mujodila', 'ru': 'Аль-Муджадала', 'en': 'Al-Mujadila'},
    59: {'ar': 'الحشر', 'uz': 'Hashr', 'ru': 'Аль-Хашр', 'en': 'Al-Hashr'},
    60: {'ar': 'الممتحنة', 'uz': 'Mumtahina', 'ru': 'Аль-Мумтахана', 'en': 'Al-Mumtahanah'},
    61: {'ar': 'الصف', 'uz': 'Sof', 'ru': 'Ас-Сафф', 'en': 'As-Saff'},
    62: {'ar': 'الجمعة', 'uz': 'Juma', 'ru': 'Аль-Джумуа', 'en': 'Al-Jumuah'},
    63: {'ar': 'المنافقون', 'uz': 'Munofiqun', 'ru': 'Аль-Мунафикун', 'en': 'Al-Munafiqun'},
    64: {'ar': 'التغابن', 'uz': 'Tag\'obun', 'ru': 'Ат-Тагабун', 'en': 'At-Taghabun'},
    65: {'ar': 'الطلاق', 'uz': 'Taloq', 'ru': 'Ат-Талак', 'en': 'At-Talaq'},
    66: {'ar': 'التحريم', 'uz': 'Tahrim', 'ru': 'Ат-Тахрим', 'en': 'At-Tahrim'},
    67: {'ar': 'الملك', 'uz': 'Mulk', 'ru': 'Аль-Мульк', 'en': 'Al-Mulk'},
    68: {'ar': 'القلم', 'uz': 'Qalam', 'ru': 'Аль-Калам', 'en': 'Al-Qalam'},
    69: {'ar': 'الحاقة', 'uz': 'Haqqa', 'ru': 'Аль-Хакка', 'en': 'Al-Haqqah'},
    70: {'ar': 'المعارج', 'uz': 'Ma\'orij', 'ru': 'Аль-Маарадж', 'en': 'Al-Maarij'},
    71: {'ar': 'نوح', 'uz': 'Nuh', 'ru': 'Нух', 'en': 'Nuh'},
    72: {'ar': 'الجن', 'uz': 'Jin', 'ru': 'Аль-Джинн', 'en': 'Al-Jinn'},
    73: {'ar': 'المزمل', 'uz': 'Muzzammil', 'ru': 'Аль-Музаммиль', 'en': 'Al-Muzzammil'},
    74: {'ar': 'المدثر', 'uz': 'Muddassir', 'ru': 'Аль-Муддассир', 'en': 'Al-Muddaththir'},
    75: {'ar': 'القيامة', 'uz': 'Qiyoma', 'ru': 'Аль-Кийама', 'en': 'Al-Qiyamah'},
    76: {'ar': 'الإنسان', 'uz': 'Inson', 'ru': 'Аль-Инсан', 'en': 'Al-Insan'},
    77: {'ar': 'المرسلات', 'uz': 'Mursalot', 'ru': 'Аль-Мурсалат', 'en': 'Al-Mursalat'},
    78: {'ar': 'النبأ', 'uz': 'Naba', 'ru': 'Ан-Наба', 'en': 'An-Naba'},
    79: {'ar': 'النازعات', 'uz': 'Noziot', 'ru': 'Ан-Назиат', 'en': 'An-Naziat'},
    80: {'ar': 'عبس', 'uz': 'Abasa', 'ru': 'Абаса', 'en': 'Abasa'},
    81: {'ar': 'التكوير', 'uz': 'Takvir', 'ru': 'Ат-Таквир', 'en': 'At-Takwir'},
    82: {'ar': 'الانفطار', 'uz': 'Infitor', 'ru': 'Аль-Инфитар', 'en': 'Al-Infitar'},
    83: {'ar': 'المطففين', 'uz': 'Mutaffifin', 'ru': 'Аль-Мутаффифин', 'en': 'Al-Mutaffifin'},
    84: {'ar': 'الانشقاق', 'uz': 'Inshiqoq', 'ru': 'Аль-Иншикак', 'en': 'Al-Inshiqaq'},
    85: {'ar': 'البروج', 'uz': 'Buruj', 'ru': 'Аль-Бурудж', 'en': 'Al-Buruj'},
    86: {'ar': 'الطارق', 'uz': 'Toriq', 'ru': 'Ат-Тарик', 'en': 'At-Tariq'},
    87: {'ar': 'الأعلى', 'uz': 'A\'lo', 'ru': 'Аль-Аля', 'en': 'Al-Ala'},
    88: {'ar': 'الغاشية', 'uz': 'G\'oshiya', 'ru': 'Аль-Гашия', 'en': 'Al-Ghashiyah'},
    89: {'ar': 'الفجر', 'uz': 'Fajr', 'ru': 'Аль-Фаджр', 'en': 'Al-Fajr'},
    90: {'ar': 'البلد', 'uz': 'Balad', 'ru': 'Аль-Балад', 'en': 'Al-Balad'},
    91: {'ar': 'الشمس', 'uz': 'Shams', 'ru': 'Аш-Шамс', 'en': 'Ash-Shams'},
    92: {'ar': 'الليل', 'uz': 'Layl', 'ru': 'Аль-Лейль', 'en': 'Al-Layl'},
    93: {'ar': 'الضحى', 'uz': 'Zuho', 'ru': 'Ад-Духа', 'en': 'Ad-Duhaa'},
    94: {'ar': 'الشرح', 'uz': 'Sharh', 'ru': 'Аш-Шарх', 'en': 'Ash-Sharh'},
    95: {'ar': 'التين', 'uz': 'Tin', 'ru': 'Ат-Тин', 'en': 'At-Tin'},
    96: {'ar': 'العلق', 'uz': 'Alaq', 'ru': 'Аль-Алак', 'en': 'Al-Alaq'},
    97: {'ar': 'القدر', 'uz': 'Qadr', 'ru': 'Аль-Кадр', 'en': 'Al-Qadr'},
    98: {'ar': 'البينة', 'uz': 'Bayyina', 'ru': 'Аль-Баййина', 'en': 'Al-Bayyinah'},
    99: {'ar': 'الزلزلة', 'uz': 'Zalzala', 'ru': 'Аз-Зальзаля', 'en': 'Az-Zalzalah'},
    100: {'ar': 'العاديات', 'uz': 'Odiyot', 'ru': 'Аль-Адият', 'en': 'Al-Adiyat'},
    101: {'ar': 'القارعة', 'uz': 'Qoria', 'ru': 'Аль-Кариа', 'en': 'Al-Qariah'},
    102: {'ar': 'التكاثر', 'uz': 'Takasur', 'ru': 'Ат-Такасур', 'en': 'At-Takathur'},
    103: {'ar': 'العصر', 'uz': 'Asr', 'ru': 'Аль-Аср', 'en': 'Al-Asr'},
    104: {'ar': 'الهمزة', 'uz': 'Humaza', 'ru': 'Аль-Хумаза', 'en': 'Al-Humazah'},
    105: {'ar': 'الفيل', 'uz': 'Fil', 'ru': 'Аль-Филь', 'en': 'Al-Fil'},
    106: {'ar': 'قريش', 'uz': 'Quraysh', 'ru': 'Курайш', 'en': 'Quraysh'},
    107: {'ar': 'الماعون', 'uz': 'Maun', 'ru': 'Аль-Маун', 'en': 'Al-Maun'},
    108: {'ar': 'الكوثر', 'uz': 'Kavsar', 'ru': 'Аль-Каусар', 'en': 'Al-Kawthar'},
    109: {'ar': 'الكافرون', 'uz': 'Kofirun', 'ru': 'Аль-Кафирун', 'en': 'Al-Kafirun'},
    110: {'ar': 'النصر', 'uz': 'Nasr', 'ru': 'Ан-Наср', 'en': 'An-Nasr'},
    111: {'ar': 'المسد', 'uz': 'Masad', 'ru': 'Аль-Масад', 'en': 'Al-Masad'},
    112: {'ar': 'الإخلاص', 'uz': 'Ixlos', 'ru': 'Аль-Ихлас', 'en': 'Al-Ikhlas'},
    113: {'ar': 'الفلق', 'uz': 'Falaq', 'ru': 'Аль-Фаляк', 'en': 'Al-Falaq'},
    114: {'ar': 'الناس', 'uz': 'Nos', 'ru': 'Ан-Нас', 'en': 'An-Nas'}
}